services:
  - type: web
    name: sabor-y-arte-backend
    runtime: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "gunicorn menu_backend.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: sabor-y-arte-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"